### ISSUE TITLE
error using bootstrap

### ISSUE THREAD

**Issue by viniciobb** [coryhouse/react-flux-building-applications#10]
I know that's not part of the course but I've been using this project as a start for react-flux projects.
Using components like dropdowns and radio-buttons doesn't work - it's ok with the css but changing doesn't take effect.

For example I took an dropdown example from https://getbootstrap.com/docs/3.3/components/#dropdowns and just created a new common component called DropDown

"use strict";
var React = require('react');
var DropDown = React.createClass({

    render: function(){
        
        return (
            <div className="dropdown">
                <button className="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    Dropdown
                    <span className="caret"></span>
                </button>
                <ul className="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" className="divider"></li>
                    <li><a href="#">Separated link</a></li>
                </ul>
            </div>
            
        ); 
    }

});

module.exports = DropDown; 

The same happens with others components like  radio for example.

**Comment by coryhouse** [comment]
I assume you mean it's not styled properly. You need to load the relevant styles as well. If you want to use Bootstrap, I'd suggest considering [React bootstrap](https://github.com/react-bootstrap/react-bootstrap/).
