### ISSUE TITLE
"npm start "throwing errors at create-react-app entry point

### ISSUE THREAD

**Issue by Shaywho** [coryhouse/react-flux-building-applications#13]
Shehus-MacBook-Pro:for-flux shehulawal$ npm start

> for-flux@0.1.0 start /Users/shehulawal/Desktop/reactproject/pers.projects/react-flux/for-flux
> run-p start:dev start:api

> for-flux@0.1.0 prestart:api /Users/shehulawal/Desktop/reactproject/pers.projects/react-flux/for-flux
> node tools/createMockDb.js

> for-flux@0.1.0 start:dev /Users/shehulawal/Desktop/reactproject/pers.projects/react-flux/for-flux
> cross-env REACT_APP_API_URL = http://localhost:3001 react-scripts start

Mock DB created.

> for-flux@0.1.0 start:api /Users/shehulawal/Desktop/reactproject/pers.projects/react-flux/for-flux
> node tools/apiServer.js

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn REACT_APP_API_URL ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! for-flux@0.1.0 start:dev: `cross-env REACT_APP_API_URL = http://localhost:3001 react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the for-flux@0.1.0 start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shehulawal/.npm/_logs/2020-04-06T13_03_48_627Z-debug.log
ERROR: "start:dev" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! for-flux@0.1.0 start: `run-p start:dev start:api`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the for-flux@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shehulawal/.npm/_logs/2020-04-06T13_03_48_702Z-debug.log
Shehus-MacBook-Pro:for-flux shehulawal$ npm start

> for-flux@0.1.0 start /Users/shehulawal/Desktop/reactproject/pers.projects/react-flux/for-flux
> run-p start:dev start:api

> for-flux@0.1.0 prestart:api /Users/shehulawal/Desktop/reactproject/pers.projects/react-flux/for-flux
> node tools/createMockDb.js

> for-flux@0.1.0 start:dev /Users/shehulawal/Desktop/reactproject/pers.projects/react-flux/for-flux
> cross-env REACT_APP_API_URL = http://localhost:3001 react-scripts start

Mock DB created.

> for-flux@0.1.0 start:api /Users/shehulawal/Desktop/reactproject/pers.projects/react-flux/for-flux
> node tools/apiServer.js

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn REACT_APP_API_URL ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! for-flux@0.1.0 start:dev: `cross-env REACT_APP_API_URL = http://localhost:3001 react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the for-flux@0.1.0 start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shehulawal/.npm/_logs/2020-04-06T13_15_12_365Z-debug.log
ERROR: "start:dev" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! for-flux@0.1.0 start: `run-p start:dev start:api`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the for-flux@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shehulawal/.npm/_logs/2020-04-06T13_15_12_433Z-debug.log

**Comment by Shaywho** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle for-flux@0.1.0~prestart: for-flux@0.1.0
6 info lifecycle for-flux@0.1.0~start: for-flux@0.1.0
7 verbose lifecycle for-flux@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle for-flux@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/shehulawal/Desktop/reactproject/pers.projects/react-flux/for-flux/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/munki
9 verbose lifecycle for-flux@0.1.0~start: CWD: /Users/shehulawal/Desktop/reactproject/pers.projects/react-flux/for-flux
10 silly lifecycle for-flux@0.1.0~start: Args: [ '-c', 'run-p start:dev start:api' ]
11 silly lifecycle for-flux@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle for-flux@0.1.0~start: Failed to exec start script
13 verbose stack Error: for-flux@0.1.0 start: `run-p start:dev start:api`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid for-flux@0.1.0
15 verbose cwd /Users/shehulawal/Desktop/reactproject/pers.projects/react-flux/for-flux
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error for-flux@0.1.0 start: `run-p start:dev start:api`
22 error Exit status 1
23 error Failed at the for-flux@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by coryhouse** [comment]
Hello, I handle support on the course discussion tab. Can you please post there? Please post your code on GitHub so I can run your project to reproduce your issue. Thanks!
