### ISSUE TITLE
addAuthor not in routes

### ISSUE THREAD

**Issue by isatemple** [coryhouse/react-flux-building-applications#3]
I had to add the following to routes.js to get the addAuthor method to work:

`<Route path="addAuthor" component={ManageAuthorPage} />`

**Comment by coryhouse** [comment]
@isatemple looks like your comment has been truncated?

**Comment by isatemple** [comment]
@coryhouse Ah, right. Forgot the code styling.

**Comment by coryhouse** [comment]
I'm confused. The addAuthor route is there in the final version of the demo: https://github.com/coryhouse/react-flux-building-applications/blob/master/src/routes.js#L15

**Comment by isatemple** [comment]
Hey @coryhouse, I was using the update branch.

**Comment by coryhouse** [comment]
Ah! Good catch! I just committed a fix to the update branch. 👍
