### ISSUE TITLE
aboutPage transition.about used instead of transition.abort

### ISSUE THREAD

**Issue by Singleton06** [coryhouse/react-flux-building-applications#6]
https://github.com/coryhouse/react-flux-building-applications/blob/master/src/components/about/aboutPage.js#L9

Instead of the code reading:
```javascript
transition.abort();
```

it reads:
```javascript
transition.about();
```

I'm pretty sure that this is just a typo, but it still works since the invocation of the callback is still branched based on the response of the confirm.

**Comment by coryhouse** [comment]
Correct, that is indeed a typo that coincidentally worked. And you're correct about my intent. I plan to update the course soon so this will be corrected at that time. Thanks though!
